config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :scientists, only: [:show]
  resources :scientist_experiments, only: [:destroy]
  resources :experiments, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/experiment.rb
class Experiment < ApplicationRecord
  has_many :scientist_experiments
  has_many :scientists, through: :scientist_experiments

  def self.long_running_experiments
    where("num_months > 6").order(num_months: :desc)
  end
end

app/models/lab.rb
class Lab < ApplicationRecord
  has_many :scientists
end

app/models/scientist.rb
class Scientist < ApplicationRecord
  belongs_to :lab
  has_many :scientist_experiments
  has_many :experiments, through: :scientist_experiments
end

app/models/scientist_experiment.rb
class ScientistExperiment < ApplicationRecord
  belongs_to :scientist
  belongs_to :experiment
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/experiments_controller.rb
class ExperimentsController < ApplicationController
  def index
    @long_running_experiments = Experiment.long_running_experiments
  end
end

app/controllers/scientist_experiments_controller.rb
class ScientistExperimentsController < ApplicationController
  def destroy
    se = ScientistExperiment.find(params[:id])
    scientist = se.scientist
    se.destroy
    redirect_to scientist_path(scientist)
  end
end

app/controllers/scientists_controller.rb
class ScientistsController < ApplicationController
  def show
    @scientist = Scientist.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/experiments/index.html.erb
<div id="long_running_experiments">
  <% @long_running_experiments.each do |lre| %>
    <div id="experiment_id-<%= lre.id%>">
      <%= lre.name %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Frankenstein</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/scientists/show.html.erb
Name: <%= @scientist.name %><br>
Specialty: <%= @scientist.specialty %><br>
University: <%= @scientist.university %><br>
Lab: <%= @scientist.lab.name %><br>

<div id="experiments">
  <% @scientist.scientist_experiments.each do |se| %>
    <div id="experiment_id-<%= se.experiment.id %>">
      <%= se.experiment.name %>
      <%= button_to "Delete", scientist_experiment_path(se.id), method: :delete %>
    </div>
  <% end %>

</div>